### PR TITLE
Fit null model in the same way as k-mers

### PR DESCRIPTION
**Pull request by johnlees**
This also corrects a small error from me being lazy with earlier code. Null model for Firth is now actually fit using Firth regression.
Makes only a small difference, e.g. p = 4.43E-47 before; p = 4.50E-47 after

I guess this might affect the tests?

### CODE REVIEW

**Comment by johnlees** [comment]
Yeah it failed -- sorry, I should have updated the tests too.

**Comment by mgalardini** [comment]
I'll quickly fix the tests, thanks again!

**Comment by mgalardini** [comment]
Turned out to be crashing for continuous phenotypes only, nothing to do with tests. We are lenient with the results, beta and -log(p-values) need to have correlation below 0.9 to trigger an error.

**Comment by mgalardini** [comment]
Nevermind, the tests are actually failing for a low correlation. I'll look into that later.

**Comment by mgalardini** [comment]
Fixed now....

**Pull request merged**
