### PR TITLE
Add shape parameter to csr_matrix in load_all_vars (#151)

### PR DESCRIPTION
**Pull request by julibeg**

### CODE REVIEW

**Comment by julibeg** [comment]
Don't merge yet. It looks like this throws a different error when running with a VCF (I encountered the original bug with .Rtab files). Gonna loo into it.

**Comment by julibeg** [comment]
The problem is that I used `len(sample_order)`, which is only present when running with `--pres`. `len(all_strains)` works always.

**Review by johnlees — CHANGES_REQUESTED** [review]
Thanks again for this important fix.
Can you bump the version in `pyseer/__init__.py` to 1.3.8? Then we'll merge and make a release as @mgalardini suggests.

**Comment by julibeg** [comment]
version has been bumped

**Review by johnlees — APPROVED** [review]

**Pull request merged**
