### PR TITLE
Add test that phenotype is numeric

### PR DESCRIPTION
**Pull request by johnlees**
Raised in #139

### CODE REVIEW

**Comment by johnlees** [comment]
@mgalardini I am still having trouble seeing the CI tests for PRs. Do you have any thoughts on maybe moving to github actions? I did this recently in PopPUNK (e.g. https://github.com/johnlees/PopPUNK/blob/master/.github/workflows/azure_ci.yml)

**Comment by mgalardini** [comment]
Hi John, sure we could do that! In the meantime if you click on the Travis CI badge you can see the tests for the branch you made, there seems to be a TypeError right now: `TypeError: Cannot construct a dtype from an array`

**Comment by johnlees** [comment]
Ok, I'll try adding that in to this PR too

**Comment by mgalardini** [comment]
I think it should be `cd tests && bash run_test.sh`? Thanks for setting this up, we can remove Travis in the next release then

**Review by mgalardini — APPROVED** [review]
Looks very good to me, sorry you had to go through so many errors because of matplotlib's backends!

**Pull request merged**
