### PR TITLE
Fix summarize_annotations when using elastic net

### PR DESCRIPTION
**Pull request by lvclark**
Using output from the elastic net model, I was getting an error because no p-value correcting for population structure was reported.  This change allows `summarize_annotations` to use the p-value that doesn't correct for population structure in that case.

### CODE REVIEW

**Comment by mgalardini** [comment]
Hi, thanks for reporting this issue and a potential solution. Maybe it would make more sense for the script to have an option to consider the filtering p-value instead of the lrt one. This way it is more explicit which pvalue is actually used and can avoid confusion. Does that make sense?

**Comment by johnlees** [comment]
@mgalardini Should we turn on travis on branches/PRs? I guess it would be useful to see the tests here 
(I also just noticed I had broken them with a recent commit, but have fixed again now)

**Comment by mgalardini** [comment]
Sure, that makes sense, let me do it then

**Comment by mgalardini** [comment]
I'm not sure why it does not show up here, but Travis is running tests for PRs: https://travis-ci.org/github/mgalardini/pyseer/builds/741672174

**Comment by johnlees** [comment]
[Quick search](https://travis-ci.community/t/github-pr-is-being-built-but-result-is-not-shown/7025/2) suggests the solution is to remove and add again -- a classic

@lvclark Would you be able to merge master into this to pull in the test fix?

**Comment by mgalardini** [comment]
Ah, of course. I did something similar, but unsure if that works. Will check later again

**Comment by lvclark** [comment]
@johnlees Ok, I've done the merge!

@mgalardini Adding an option to the script makes sense.  I wasn't sure if you'd actually want to merge this PR, but I wanted to at least bring the issue to your attention!

**Comment by johnlees** [comment]
I'd suggest that we merge this, and then add the script option. I can do this shortly

**Pull request merged**
