### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by mgalardini**

### CODE REVIEW

**Review by johnlees — APPROVED** [review]

**Comment by mgalardini** [comment]
Thanks; I don't think I did anything last time to get the conda recipe updated. I think it may be automagic. We'll see...

**Comment by mgalardini** [comment]
So last time I actually had to commit the recipe myself, but now they are doing it automagically https://github.com/bioconda/bioconda-recipes/pull/28300

**Comment by johnlees** [comment]
Looks like it all worked this time, I've just merged it

**Comment by mgalardini** [comment]
Great thanks!

**Pull request merged**
